version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - mkdir node_modules
      - npm install --omit=dev
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '.platform/**/*'
    - package.json
    - package-lock.json
    - '.env.*'
    - 'build/**/*'
  discard-paths: no